Tidied up our examples
Fixes to initd and compose-server-initd scripts embedded in compose-service.sh

Example Use added to README

diff --git a/examples/compose-service.init b/examples/compose-service.init
--- a/examples/compose-service.init
+++ b/examples/compose-service.init
@@ -1,45 +1,85 @@
-#!/bin/sh
 ### BEGIN INIT INFO
-# Provides:		compose-service
-# Required-Start:	$docker
-# Required-Stop:	$docker
+# Provides:		YOUR_SERVICE
+# Required-Start:	\$docker
+# Required-Stop:	\$docker
 # Default-Start:	2 3 4 5
 # Default-Stop:		0 1 6
-# Short-Description:	Docker Compose Service Manager
+# Short-Description:	compose-service for $SERVICE_NAME
 ### END INIT INFO
 
 set -e
 
 
-SERVICE_NAME="compose-service"
-UPOPTS="-d --no-recreate --no-build --no-deps"
 
- 
-. /lib/lsb/init-functions
+###############################################
+### you can explicitly set the compose parameters
+###############################################
+SERVICE_NAME=YOUR-SERVICE
+SERVICE_DEPLOYMENT=/path/to/yml
+
+
+###############################################
+## Below is how the compose-service.sh loads
+## the data from a deployment configuration file
+###############################################
+
+#SERVICE_CONFIG is populated at install time
+SERVICE_CONFIG=/etc/compose-service/service.d/YOUR-SERVICE.service
+
+if [[ ! -f \$SERVICE_CONFIG || ! -r \$SERVICE_CONFIG ]]; then
+    log_daemon_msg "Could Not find compose-service configuration - service broken"
+    exit 1
+fi
+
+source $SERVICE_CONFIG
+
+if [[ -z \$SERVICE_NAME || -z \$SERVICE_DEPLOYMENT ]]; then
+    log_daemon_msg "Compose-service config loaded but malformed - service broken"
+    exit 1
+fi
+
+
+
+
+OPTS="-f $SERVICE_DEPLOYMENT -p $SERVICE_NAME "
+UPOPTS="-d --no-recreate --no-build --no-deps"
+ . /lib/lsb/init-functions
 
 case "$1" in
     start)
-        log_daemon_msg "Starting compose-server service" "$SERVICE_NAME" ||  true
-        docker-compose $OPTS up $UPOPTS
+        log_daemon_msg "Starting compose-service" "$SERVICE_NAME" ||  true
+        docker-compose $OPTS up $UPOPTS 
         ;;
 
     stop)
-        log_daemon_msg "Stopping GOGS Git Server VIA Docker Compose" "composegogs" || true
-        docker-compose $OPTS stop
+        log_daemon_msg "Stopping compose-service" "$SERVICE_NAME" || true
+        docker-compose $OPTS stop 
+        ;;
+
+    down)
+        log_daemon_msg "Stoping compose-service" "$SERVICE_NAME" || true
+        docker-compose $OPTS down    
         ;;
 
     reload)
-        log_daemon_msg "Reloading GOGS Git Server VIA Docker Compose" "composegogs" || true
+        log_daemon_msg "Reloading compose-service" "$SERVICE_NAME" || true
         docker-compose $OPTS up $UPOPTS
         ;;
 
     restart)
+        log_daemon_msg "Restarting compose-service" "$SERVICE_NAME" || true
         docker-compose $OPTS stop
         docker-compose $OPTS up $UPOPTS
         ;;
 
+    recreate)
+        log_daemon_msg "Recreating compose-service" "$SERVICE_NAME" || true
+        docker-compose $OPTS down
+        docker-compose $OPTS up $UPOPTS
+        ;;
+
     *)
-        log_action_msg "Usage: /etc/init.d/composegogs {start|stop|restart|reload}" || true
+        log_action_msg "Usage: /etc/init.d/composegogs {start|stop|down|restart|reload|recreate}" || true
         exit 1
         ;;
 esac
